export const copy = {
  site: {
    pageTitle: (officeName: string) => `Strona startowa — ${officeName}`,
    metaDescription: "Wewnętrzna strona startowa dla pracowników urzędu",
    subtitle: "Informacje dla pracowników",
  },
  sections: {
    quickLinks: "Szybkie linki",
    cert: "Ostrzeżenia CERT Polska",
    announcements: "Ogłoszenia wewnętrzne",
    acknowledge: "Potwierdzenie zapoznania się",
  },
  quickLinksPanel: {
    collapse: "Zwiń linki",
    expand: "Rozwiń linki",
  },
  empty: {
    cert: "Brak aktualnych ostrzeżeń.",
    announcements: "Brak ogłoszeń.",
    links: "Brak linków.",
    users: "Brak użytkowników.",
    acknowledgments: "Brak potwierdzeń.",
    pageViews: "Brak odwiedzin w rejestrze.",
    certCategories:
      "Brak kategorii do skonfigurowania — nie udało się pobrać ostrzeżeń lub nie mają one kategorii.",
  },
  badges: {
    pinned: "Przypięte",
    critical: "Krytyczne",
  },
  actions: {
    manage: "Zarządzaj",
    login: "Zaloguj",
    logout: "Wyloguj",
    save: "Zapisz",
    edit: "Edytuj",
    saveChanges: "Zapisz zmiany",
    details: "Szczegóły",
    loginSettings: "Tryb logowania",
    delete: "Usuń",
    changeRole: "Zmień rolę",
    resetPin: "Reset PIN",
    addAnnouncement: "Dodaj ogłoszenie",
    addLink: "Dodaj link",
    addUser: "Dodaj użytkownika",
    saveLink: "Zapisz link",
    saveHeader: "Zapisz nagłówek",
    saveCertCategories: "Zapisz ustawienia kategorii",
    clearAcknowledgments: "Wyczyść rejestr",
    clearPageViews: "Wyczyść rejestr",
    acknowledge: "Potwierdzam zapoznanie",
    uploadLogo: "Wgraj logo",
    removeLogo: "Usuń logo",
  },
  labels: {
    password: "Hasło",
    pin: "PIN",
    logoFile: "Plik logo (PNG, JPG, WebP lub SVG, max. 2 MB)",
    headerTitle: "Tytuł nagłówka",
    headerSubtitle: "Podtytuł nagłówka",
    title: "Tytuł",
    body: "Treść",
    pinned: "Przypięte",
    linkName: "Nazwa",
    linkUrl: "Adres URL",
    linkDescription: "Opis (opcjonalnie)",
    fullName: "Imię i nazwisko",
    role: "Rola",
    newPin: "Nowy PIN",
  },
  roles: {
    reader: "Czytelnik",
    editor: "Edytor",
    admin: "Administrator",
  },
  admin: {
    title: "Panel administracyjny",
    loginHint: "Zaloguj się, aby zarządzać treścią strony.",
    notConfigured:
      "Panel nie jest skonfigurowany. Ustaw zmienną środowiskową ADMIN_PASSWORD.",
    wrongPassword: "Nieprawidłowe hasło. Spróbuj ponownie.",
    rateLimited: "Zbyt wiele prób logowania. Spróbuj ponownie za chwilę.",
    csrfFailed: "Sesja wygasła lub żądanie jest nieprawidłowe. Odśwież stronę i spróbuj ponownie.",
    unauthorized: "Brak autoryzacji. Zaloguj się ponownie.",
    certCategoriesTitle: "Kategorie CERT na stronie głównej",
    certCategoriesHelp:
      "Odznacz kategorie, których ostrzeżenia mają być ukryte na stronie głównej.",
    boardTab: "Tablica",
    settingsTab: "Ustawienia",
    boardAnnouncementsSubtab: "Ogłoszenia",
    boardLinksSubtab: "Linki",
    boardCertSubtab: "CERT",
    settingsTitle: "Wygląd strony",
    addAnnouncement: "Nowe ogłoszenie",
    existingAnnouncements: "Ogłoszenia",
    addLink: "Nowy szybki link",
    quickLinks: "Szybkie linki",
    acknowledgments: "Rejestr potwierdzeń",
    pageViews: "Rejestr odwiedzin",
    pageViewsHelp:
      "Automatyczny zapis wejść na stronę główną i panel admina. Pozwala sprawdzić, czy pracownicy korzystają ze strony — niezależnie od potwierdzeń.",
    pageViewsStatsVisits: (count: number) =>
      `Odwiedziny strony głównej (7 dni): ${count}`,
    pageViewsStatsHosts: (count: number) =>
      `Unikalne hosty (7 dni): ${count}`,
    pageViewsLastVisit: (date: string, host: string) =>
      `Ostatnia wizyta na stronie głównej: ${date} — ${host}`,
    pageViewsNoLastVisit: "Brak odwiedzin strony głównej w rejestrze.",
    pageViewsCleared: "Rejestr odwiedzin został wyczyszczony.",
    headerTitle: "Nagłówek strony",
    headerPreview: "Podgląd nagłówka",
    headerTextForm: "Teksty nagłówka",
    logoForm: "Logo",
    logoHelp:
      "Wyświetlane obok tekstów w nagłówku. Zalecany format poziomy (PNG/SVG z przezroczystością, JPG lub WebP).",
    logoMissing: "Brak wgranego logo.",
    headerSaved: "Nagłówek został zapisany.",
    headerInvalid: "Tytuł nagłówka nie może być pusty.",
    logoSaved: "Logo zostało zapisane.",
    logoRemoved: "Logo zostało usunięte.",
    logoInvalid:
      "Nie udało się wgrać logo. Dozwolone: PNG, JPG, WebP lub SVG, maks. 2 MB.",
    announcementAdded: "Ogłoszenie zostało dodane.",
    announcementUpdated: "Ogłoszenie zostało zapisane.",
    announcementDeleted: "Ogłoszenie zostało usunięte.",
    announcementInvalid: "Tytuł i treść ogłoszenia są wymagane.",
    linkAdded: "Link został dodany.",
    linkUpdated: "Link został zapisany.",
    linkDeleted: "Link został usunięty.",
    linkInvalid: "Podaj nazwę i poprawny adres URL (https://).",
    certCategoriesSaved: "Ustawienia kategorii CERT zostały zapisane.",
    acknowledgmentsCleared: "Rejestr potwierdzeń został wyczyszczony.",
    usersTitle: "Użytkownicy",
    usersHelp:
      "Konta pracowników do logowania na stronie głównej. Admin tworzy użytkownika z imieniem, rolą i PIN-em (4–6 cyfr).",
    userLoginModeTitle: "Tryb logowania",
    userLoginModeSelect: "Lista wyboru (imię z listy + PIN)",
    userLoginModeType: "Wpisywanie imienia i nazwiska (bez podpowiedzi) + PIN",
    userLoginModeSaved: "Tryb logowania został zapisany.",
    userCreated: "Użytkownik został utworzony.",
    userUpdated: "Rola użytkownika została zapisana.",
    userPinReset: "PIN użytkownika został zmieniony.",
    userDeleted: "Użytkownik został usunięty.",
    userInvalid: "Podaj imię, rolę i PIN (4–6 cyfr).",
    userExists: "Użytkownik o tym imieniu już istnieje.",
    userStatsTitle: "Statystyki użytkowników",
    userStatsVisits7: (name: string, count: number) =>
      `${name} — odwiedziny (7 dni): ${count}`,
    userStatsVisits30: (name: string, count: number) =>
      `${name} — odwiedziny (30 dni): ${count}`,
    userStatsLastVisit: (name: string, date: string, host: string) =>
      `${name} — ostatnia wizyta: ${date} — ${host}`,
    statsVisits7: "Odwiedziny (7 dni)",
    statsVisits30: "Odwiedziny (30 dni)",
    statsLastVisit: "Ostatnia wizyta",
    detailPath: "Ścieżka",
    detailHost: "Host",
    detailDate: "Data",
    editorOnlyAnnouncements:
      "Masz dostęp tylko do zarządzania ogłoszeniami.",
    readerNoAdmin: "Brak dostępu do panelu administracyjnego.",
  },
  userSession: {
    loggedInAs: (name: string) => `Zalogowany: ${name}`,
    selectUser: "Wybierz…",
    loginFailed: "Nieprawidłowe dane logowania.",
    rateLimited: "Zbyt wiele prób logowania. Spróbuj ponownie za chwilę.",
  },
  acknowledge: {
    intro:
      "Potwierdzam zapoznanie z ostrzeżeniami CERT oraz treścią strony głównej.",
    loginRequired: "Zaloguj się w nagłówku, aby potwierdzić zapoznanie.",
    thanks: (name: string) => `Dziękujemy, ${name}.`,
    confirmedAt: (date: string) => `Potwierdzenie zapisane: ${date}.`,
    invalidName: "Podaj imię i nazwisko (min. 1 znak).",
    rateLimited: "Zbyt wiele prób. Spróbuj ponownie za chwilę.",
    saveFailed: "Nie udało się zapisać potwierdzenia. Spróbuj ponownie.",
  },
  clock: {
    loading: "Ładowanie…",
    ariaLabel: "Aktualna data i godzina",
  },
  theme: {
    switchToLight: "Włącz tryb jasny",
    switchToDark: "Włącz tryb ciemny",
  },
  personalLinks: {
    title: "Twoje linki",
    add: "Dodaj własny link",
    remove: "Usuń link",
    badge: "Twój",
    emptyLabel: "Podaj nazwę linku.",
    invalidUrl: "Adres URL musi zaczynać się od https://",
    limitReached: (max: number) =>
      `Możesz dodać maksymalnie ${max} własnych linków.`,
    loginRequired: "Zaloguj się, aby dodać własne linki.",
  },
} as const;

export function withCount(label: string, count: number): string {
  return `${label} (${count})`;
}
